export const TEXAS_UNIVERSITY_SOURCE = "https://apps.highered.texas.gov/index.cfm?page=8303C0B742D6A6217C4E7EB75A775804AD92F671EEA28FA27DEB32DFB4609513";

const PUBLIC_UNIVERSITIES = [
  "Angelo State University",
  "East Texas A&M University",
  "Lamar University",
  "Midwestern State University",
  "Prairie View A&M University",
  "Sam Houston State University",
  "Stephen F. Austin State University",
  "Sul Ross State University",
  "Sul Ross State University Rio Grande College",
  "Tarleton State University",
  "Texas A&M International University",
  "Texas A&M University",
  "Texas A&M University at Galveston",
  "Texas A&M University System",
  "Texas A&M University-Central Texas",
  "Texas A&M University-Corpus Christi",
  "Texas A&M University-Kingsville",
  "Texas A&M University-San Antonio",
  "Texas A&M University-Texarkana",
  "Texas A&M University-Victoria",
  "Texas Southern University",
  "Texas State University",
  "Texas State University System",
  "Texas Tech University",
  "Texas Tech University System",
  "Texas Woman's University",
  "The University of Texas at Arlington",
  "The University of Texas at Austin",
  "The University of Texas at Austin-University Extension",
  "The University of Texas at Dallas",
  "The University of Texas at El Paso",
  "The University of Texas at San Antonio",
  "The University of Texas at Tyler",
  "The University of Texas Permian Basin",
  "The University of Texas Rio Grande Valley",
  "The University of Texas System",
  "University of Houston",
  "University of Houston System",
  "University of Houston-Clear Lake",
  "University of Houston-Downtown",
  "University of North Texas",
  "University of North Texas at Dallas",
  "University of North Texas System",
  "UNT Dallas College of Law",
  "West Texas A&M University",
];

const INDEPENDENT_UNIVERSITIES = [
  "Abilene Christian University",
  "Amberton University",
  "Austin College",
  "Baylor University",
  "College of Biblical Studies",
  "Concordia University Texas",
  "Criswell College",
  "Dallas Baptist University",
  "East Texas Baptist University",
  "Hardin-Simmons University",
  "Houston Christian University",
  "Howard Payne University",
  "Huston-Tillotson University",
  "Jarvis Christian University",
  "LeTourneau University",
  "Lubbock Christian University",
  "McMurry University",
  "Nelson University",
  "Our Lady of the Lake University of San Antonio",
  "Paul Quinn College",
  "Rice University",
  "Schreiner University",
  "South Texas College of Law Houston",
  "Southern Methodist University",
  "Southwestern Adventist University",
  "Southwestern Christian College",
  "Southwestern University",
  "St. Edward's University",
  "St. Mary's University",
  "Texas Christian University",
  "Texas College",
  "Texas Lutheran University",
  "Texas Wesleyan University",
  "Trinity University",
  "University of Dallas",
  "University of Mary Hardin-Baylor",
  "University of St. Thomas",
  "University of the Incarnate Word",
  "Wayland Baptist University",
  "Wiley University",
];

function directoryEntry(name, category) {
  return {
    id: `texas-${name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    name,
    category,
    location: "Texas",
  };
}

export const TEXAS_UNIVERSITIES = [
  ...PUBLIC_UNIVERSITIES.map((name) => directoryEntry(name, "Public university")),
  ...INDEPENDENT_UNIVERSITIES.map((name) => directoryEntry(name, "Independent university")),
];
