export const ASU_SYLLABUS_REQUIREMENT_PROFILE = Object.freeze({
  id: "asu-cdli-2026",
  institution: "Angelo State University",
  profileVersion: "2026.1",
  effectiveFrom: "2026-02-03",
  effectiveTo: "2027-02-03",
  sourceDocuments: [
    "Syllabus Checklist 2026",
    "Syllabus Content Guidelines 2022, modified 2026-07-22",
  ],
  authorities: [
    "HB 2504 Section 51.974",
    "Texas Administrative Code Title 19",
    "Texas Higher Education Coordinating Board",
    "SACSCOC",
    "AACSB",
    "ASU OP 04.11",
    "ASU OP 06.14",
    "ASU OP 10.10",
    "ASU OP 10.19",
    "ASU OP 10.24",
    "ASU OP 10.26",
    "ASU OP 16.03",
    "ASU OP 24.03",
    "ASU Catalog Academic Regulations",
    "Academic Course Guide Manual",
  ],
  sections: [
    {
      key: "description",
      label: "Description",
      requirement: "required",
      ownership: "course_or_institution",
      fields: [
        { key: "catalogDescription", label: "Aligned course description", required: true },
        { key: "acgmAlignment", label: "ACGM or catalog alignment", required: true },
        { key: "prerequisiteKnowledge", label: "Prerequisite knowledge or courses", required: true },
        { key: "technicalCompetencies", label: "Technical skills or other competencies", required: true },
      ],
      validationNotes: [
        "Lower-division ACGM courses should use the approved ACGM description word for word.",
        "Otherwise the description should match the relevant approved catalog description.",
      ],
    },
    {
      key: "contactInformation",
      label: "Contact Information",
      requirement: "required",
      ownership: "section_instructor",
      fields: [
        { key: "instructorTitle", label: "Instructor title", required: true },
        { key: "instructorName", label: "Instructor name", required: true },
        { key: "phone", label: "Phone number", required: true },
        { key: "asuEmail", label: "ASU email address", required: true },
        { key: "officeLocation", label: "Office location", required: true },
        { key: "otherContact", label: "Other means of contact", required: false },
        { key: "officeHours", label: "Office hours or outside-of-class contact hours", required: true },
      ],
      validationNotes: ["Official electronic communication must use the assigned ASU email address."],
    },
    {
      key: "courseDelivery",
      label: "Course Delivery",
      requirement: "required",
      ownership: "section_instructor",
      fields: [
        { key: "modality", label: "Teaching modality", required: true },
        { key: "meetingPattern", label: "Meeting days and times", required: "conditional" },
        { key: "meetingLocation", label: "Meeting location", required: "conditional" },
        { key: "lmsUse", label: "Learning Management System use", required: true },
        { key: "regularSubstantiveInteraction", label: "Regular and substantive interaction plan", required: "online_only" },
      ],
    },
    {
      key: "textsAndMaterials",
      label: "Texts and Materials",
      requirement: "required",
      ownership: "course_or_section",
      fields: [
        { key: "requiredReadings", label: "Required readings", required: true },
        { key: "recommendedReadings", label: "Recommended readings", required: true },
        { key: "requiredMaterials", label: "Required supplies and materials", required: true },
        { key: "hardware", label: "Required hardware", required: true },
        { key: "software", label: "Required software", required: true },
        { key: "subscriptions", label: "Required subscriptions", required: true },
        { key: "acquisitionSource", label: "Where materials may be obtained", required: true },
      ],
    },
    {
      key: "outcomes",
      label: "Outcomes",
      requirement: "required",
      ownership: "course_or_program",
      fields: [
        { key: "courseOutcomes", label: "Measurable course learning outcomes", required: true },
        { key: "assessmentMethods", label: "Methods used to assess outcomes", required: true },
        { key: "acgmOutcomes", label: "Applicable ACGM/core outcomes", required: "conditional" },
        { key: "accreditationAlignment", label: "Accreditation alignment", required: "conditional" },
      ],
    },
    {
      key: "objectives",
      label: "Objectives",
      requirement: "optional_by_program_or_department",
      ownership: "course_or_program",
      fields: [
        { key: "courseObjectives", label: "Measurable course objectives using active verbs", required: false },
      ],
    },
    {
      key: "gradingCriteria",
      label: "Grading Criteria",
      requirement: "required",
      ownership: "course_or_section",
      fields: [
        { key: "gradingScale", label: "ASU grading scale", required: true },
        { key: "gradeBreakdown", label: "Final grade component breakdown", required: true },
        { key: "majorRequirements", label: "Major assignments and examinations with brief descriptions", required: true },
        { key: "gradingPolicies", label: "Curves, extra credit, dropped grades, participation, and related policies", required: true },
        { key: "finalAssessmentType", label: "Final examination or culminating experience", required: true },
        { key: "finalExamDate", label: "Final examination date", required: "exam_only" },
        { key: "finalExamTime", label: "Final examination time", required: "exam_only" },
        { key: "finalExamLocation", label: "Final examination location", required: "exam_only" },
      ],
    },
    {
      key: "courseExpectations",
      label: "Course Expectations",
      requirement: "required",
      ownership: "section_instructor",
      fields: [
        { key: "attendance", label: "Attendance expectations", required: true },
        { key: "participation", label: "Participation expectations", required: true },
        { key: "communication", label: "Communication expectations", required: true },
        { key: "academicBehavior", label: "Academic behavior expectations", required: true },
        { key: "onlineConduct", label: "Online conduct expectations", required: true },
        { key: "aiUsePolicy", label: "Instructor-specific AI use policy", required: true },
        { key: "accessibilityProcess", label: "Accessibility or accommodation process", required: true },
      ],
      validationNotes: ["The instructor-specific AI policy should align with ASU OP 10.26."],
    },
    {
      key: "programInformation",
      label: "Program Information",
      requirement: "optional_by_program_or_department",
      ownership: "program_or_department",
      fields: [
        { key: "programContext", label: "Program or degree information", required: false },
        { key: "departmentRequirements", label: "Department-specific requirements", required: false },
      ],
    },
    {
      key: "institutionalPolicies",
      label: "Institutional Policies and Procedures",
      requirement: "required_institution_managed",
      ownership: "institution_locked",
      fields: [
        { key: "academicIntegrity", label: "Academic Integrity and Honor Code", required: true },
        { key: "studentDisabilities", label: "Reasonable accommodations for students with disabilities", required: true },
        { key: "titleIX", label: "Title IX and misconduct policy", required: true },
        { key: "religiousHolyDay", label: "Religious holy day absence policy", required: true },
        { key: "studentHandbook", label: "Student Handbook link", required: true },
      ],
    },
    {
      key: "additionalItems",
      label: "Additional Items",
      requirement: "optional_by_program_or_department",
      ownership: "institution_department_or_section",
      fields: [
        { key: "studentEvaluation", label: "Student evaluation of faculty and course", required: false },
        { key: "turnitin", label: "TurnItIn guidance", required: false },
        { key: "plagiarism", label: "Plagiarism guidance", required: false },
        { key: "copyright", label: "Copyright guidance", required: false },
        { key: "incompleteGrade", label: "Incomplete grade guidance", required: false },
        { key: "courseDrop", label: "Course drop guidance", required: false },
        { key: "gradeAppeal", label: "Grade appeal guidance", required: false },
        { key: "basicNeeds", label: "Basic needs resources", required: false },
        { key: "syllabusChanges", label: "Faculty syllabus change policy", required: false },
        { key: "technicalDifficulties", label: "Server unavailability or technical difficulties", required: false },
        { key: "technicalSupport", label: "Technical support resources", required: false },
        { key: "academicSupport", label: "Academic support resources", required: false },
        { key: "libraryServices", label: "Library services", required: false },
      ],
    },
    {
      key: "courseOutline",
      label: "Course Outline",
      requirement: "required",
      ownership: "course_or_section",
      fields: [
        { key: "lectureDiscussionSchedule", label: "General subject matter of each lecture or discussion", required: true },
        { key: "majorAssignments", label: "Major assignments", required: true },
        { key: "majorExaminations", label: "Major examinations", required: true },
        { key: "topicsAndDates", label: "Detailed topic and assignment schedule where reasonably possible", required: true },
      ],
    },
  ],
});

export function requiredSyllabusFields(profile = ASU_SYLLABUS_REQUIREMENT_PROFILE) {
  return profile.sections.flatMap((section) =>
    section.fields
      .filter((field) => field.required === true)
      .map((field) => ({ section: section.key, ...field })),
  );
}
