create index courses_owner_id_idx on public.courses(owner_id);
create index course_memberships_user_id_idx on public.course_memberships(user_id);
create index assignments_course_id_idx on public.assignments(course_id);
create index assignments_professor_id_idx on public.assignments(professor_id);
create index learning_resources_owner_id_idx on public.learning_resources(owner_id);
create index learning_resources_course_id_idx on public.learning_resources(course_id);
create index learning_resources_assignment_id_idx on public.learning_resources(assignment_id);
create index learning_resources_course_placement_idx on public.learning_resources(course_id,placement,created_at desc);
create index rubrics_owner_id_idx on public.rubrics(owner_id);
create index assignment_drafts_student_id_idx on public.assignment_drafts(student_id);
create index learning_messages_course_id_idx on public.learning_messages(course_id,created_at desc);
create index learning_messages_assignment_id_idx on public.learning_messages(assignment_id);
create index learning_messages_sender_id_idx on public.learning_messages(sender_id);
create index learning_messages_recipient_id_idx on public.learning_messages(recipient_id);
create index learning_messages_attachment_resource_id_idx on public.learning_messages(attachment_resource_id);
create index publications_owner_id_idx on public.publications(owner_id);
create index publications_course_id_idx on public.publications(course_id);
create index reading_annotations_publication_id_idx on public.reading_annotations(publication_id);
create index reading_annotations_user_id_idx on public.reading_annotations(user_id);
create index publisher_applications_applicant_id_idx on public.publisher_applications(applicant_id);
create index slide_decks_owner_id_idx on public.slide_decks(owner_id);
create index slide_decks_course_id_idx on public.slide_decks(course_id);

alter policy courses_select on public.courses using (owner_id=(select auth.uid()) or private.can_access_course(id));
alter policy courses_insert on public.courses with check (owner_id=(select auth.uid()));
alter policy course_memberships_select on public.course_memberships using (user_id=(select auth.uid()) or private.can_manage_course(course_id));
alter policy learning_resources_select on public.learning_resources using (owner_id=(select auth.uid()) or (course_id is not null and private.can_access_course(course_id) and visibility in ('course','public','publisher')));
alter policy learning_resources_insert on public.learning_resources with check (owner_id=(select auth.uid()) and (course_id is null or private.can_access_course(course_id)));
alter policy learning_resources_update on public.learning_resources using (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id))) with check (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id)));
alter policy learning_resources_delete on public.learning_resources using (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id)));
alter policy assignments_insert on public.assignments with check (professor_id=(select auth.uid()) and private.can_manage_course(course_id));
alter policy rubrics_select on public.rubrics using (owner_id=(select auth.uid()) or private.can_access_assignment(assignment_id));
alter policy rubrics_insert on public.rubrics with check (owner_id=(select auth.uid()) and private.can_manage_assignment(assignment_id));
alter policy rubrics_update on public.rubrics using (owner_id=(select auth.uid()) or private.can_manage_assignment(assignment_id)) with check (owner_id=(select auth.uid()) or private.can_manage_assignment(assignment_id));
alter policy rubrics_delete on public.rubrics using (owner_id=(select auth.uid()) or private.can_manage_assignment(assignment_id));
alter policy assignment_drafts_select on public.assignment_drafts using (student_id=(select auth.uid()) or private.can_manage_assignment(assignment_id));
alter policy assignment_drafts_insert on public.assignment_drafts with check (student_id=(select auth.uid()) and private.can_access_assignment(assignment_id));
alter policy assignment_drafts_update on public.assignment_drafts using (student_id=(select auth.uid())) with check (student_id=(select auth.uid()));
alter policy assignment_drafts_delete on public.assignment_drafts using (student_id=(select auth.uid()) or private.can_manage_assignment(assignment_id));
alter policy learning_messages_select on public.learning_messages using (sender_id=(select auth.uid()) or recipient_id=(select auth.uid()) or (recipient_id is null and course_id is not null and private.can_access_course(course_id)));
alter policy learning_messages_insert on public.learning_messages with check (sender_id=(select auth.uid()) and (course_id is null or private.can_access_course(course_id)) and (assignment_id is null or private.can_access_assignment(assignment_id)));
alter policy learning_messages_delete on public.learning_messages using (sender_id=(select auth.uid()) or private.is_platform_manager());
alter policy publications_select on public.publications using (owner_id=(select auth.uid()) or status='published' or (course_id is not null and private.can_access_course(course_id)));
alter policy publications_insert on public.publications with check (owner_id=(select auth.uid()) and (course_id is null or private.can_manage_course(course_id)));
alter policy publications_update on public.publications using (owner_id=(select auth.uid()) or private.is_platform_manager()) with check (owner_id=(select auth.uid()) or private.is_platform_manager());
alter policy publications_delete on public.publications using (owner_id=(select auth.uid()) or private.is_platform_manager());
alter policy reading_annotations_select on public.reading_annotations using (user_id=(select auth.uid()));
alter policy reading_annotations_insert on public.reading_annotations with check (user_id=(select auth.uid()));
alter policy reading_annotations_update on public.reading_annotations using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()));
alter policy reading_annotations_delete on public.reading_annotations using (user_id=(select auth.uid()));
alter policy publisher_applications_select on public.publisher_applications using (applicant_id=(select auth.uid()) or private.is_platform_manager());
alter policy publisher_applications_insert on public.publisher_applications with check (applicant_id=(select auth.uid()));
alter policy publisher_applications_update on public.publisher_applications using (applicant_id=(select auth.uid()) or private.is_platform_manager()) with check (applicant_id=(select auth.uid()) or private.is_platform_manager());
alter policy publisher_applications_delete on public.publisher_applications using (applicant_id=(select auth.uid()) or private.is_platform_manager());
alter policy slide_decks_select on public.slide_decks using (owner_id=(select auth.uid()) or (course_id is not null and private.can_access_course(course_id)));
alter policy slide_decks_insert on public.slide_decks with check (owner_id=(select auth.uid()) and (course_id is null or private.can_access_course(course_id)));
alter policy slide_decks_update on public.slide_decks using (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id))) with check (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id)));
alter policy slide_decks_delete on public.slide_decks using (owner_id=(select auth.uid()) or (course_id is not null and private.can_manage_course(course_id)));
