insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values
('ed-private-vault','ed-private-vault',false,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/epub+zip','application/json','application/zip','text/plain','text/markdown','text/csv','image/jpeg','image/png','image/webp','image/gif','audio/mpeg','audio/wav','audio/mp4','video/mp4']),
('ed-course-materials','ed-course-materials',false,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/epub+zip','application/json','application/zip','text/plain','text/markdown','text/csv','image/jpeg','image/png','image/webp','image/gif','audio/mpeg','audio/wav','audio/mp4','video/mp4']),
('ed-submissions','ed-submissions',false,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/json','application/zip','text/plain','text/markdown','text/csv','image/jpeg','image/png','image/webp','image/gif','audio/mpeg','audio/wav','audio/mp4','video/mp4']),
('ed-publications','ed-publications',false,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/epub+zip','application/json','application/zip','text/plain','text/markdown','image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy private_vault_select on storage.objects for select to authenticated using (bucket_id='ed-private-vault' and (storage.foldername(name))[1]=auth.uid()::text);
create policy private_vault_insert on storage.objects for insert to authenticated with check (bucket_id='ed-private-vault' and (storage.foldername(name))[1]=auth.uid()::text);
create policy private_vault_update on storage.objects for update to authenticated using (bucket_id='ed-private-vault' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='ed-private-vault' and (storage.foldername(name))[1]=auth.uid()::text);
create policy private_vault_delete on storage.objects for delete to authenticated using (bucket_id='ed-private-vault' and (storage.foldername(name))[1]=auth.uid()::text);

create policy course_materials_select on storage.objects for select to authenticated using (bucket_id='ed-course-materials' and private.can_access_course(((storage.foldername(name))[1])::uuid));
create policy course_materials_insert on storage.objects for insert to authenticated with check (bucket_id='ed-course-materials' and (storage.foldername(name))[2]=auth.uid()::text and private.can_access_course(((storage.foldername(name))[1])::uuid));
create policy course_materials_update on storage.objects for update to authenticated using (bucket_id='ed-course-materials' and ((storage.foldername(name))[2]=auth.uid()::text or private.can_manage_course(((storage.foldername(name))[1])::uuid))) with check (bucket_id='ed-course-materials' and ((storage.foldername(name))[2]=auth.uid()::text or private.can_manage_course(((storage.foldername(name))[1])::uuid)));
create policy course_materials_delete on storage.objects for delete to authenticated using (bucket_id='ed-course-materials' and ((storage.foldername(name))[2]=auth.uid()::text or private.can_manage_course(((storage.foldername(name))[1])::uuid)));

create policy submissions_select on storage.objects for select to authenticated using (bucket_id='ed-submissions' and ((storage.foldername(name))[3]=auth.uid()::text or private.can_manage_assignment(((storage.foldername(name))[2])::uuid)));
create policy submissions_insert on storage.objects for insert to authenticated with check (bucket_id='ed-submissions' and (storage.foldername(name))[3]=auth.uid()::text and private.can_access_assignment(((storage.foldername(name))[2])::uuid));
create policy submissions_update on storage.objects for update to authenticated using (bucket_id='ed-submissions' and (storage.foldername(name))[3]=auth.uid()::text) with check (bucket_id='ed-submissions' and (storage.foldername(name))[3]=auth.uid()::text);
create policy submissions_delete on storage.objects for delete to authenticated using (bucket_id='ed-submissions' and ((storage.foldername(name))[3]=auth.uid()::text or private.can_manage_assignment(((storage.foldername(name))[2])::uuid)));

create policy publications_storage_select on storage.objects for select to authenticated using (bucket_id='ed-publications' and (storage.foldername(name))[1]=auth.uid()::text);
create policy publications_storage_insert on storage.objects for insert to authenticated with check (bucket_id='ed-publications' and (storage.foldername(name))[1]=auth.uid()::text);
create policy publications_storage_update on storage.objects for update to authenticated using (bucket_id='ed-publications' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='ed-publications' and (storage.foldername(name))[1]=auth.uid()::text);
create policy publications_storage_delete on storage.objects for delete to authenticated using (bucket_id='ed-publications' and (storage.foldername(name))[1]=auth.uid()::text);
